#!/usr/bin/env -S expect -f

set gitHubEnvFile cache_key_02.txt
set ::env(GITHUB_ENV) $gitHubEnvFile
set gitHubOutputFile cache_key_output_02.txt
set ::env(GITHUB_OUTPUT) $gitHubOutputFile

set timeout 3
spawn ../../bin/cache_key.sh "Linux" "8.1.1" "" "" "long-files-hash"
match_max 100000

expect -exact "::debug::Cache primary key is 'Linux-php-8.1.1-composer-locked-long-files-hash'"
expect -exact "::debug::Cache restore keys are 'Linux-php-8.1.1-composer-locked-'"
expect eof

set fp [open $gitHubEnvFile r]
set fileData [read $fp]
close $fp

set expectedValue "CACHE_RESTORE_KEY<<EOF
Linux-php-8.1.1-composer-locked-
EOF
"

if { $expectedValue != $fileData } {
    puts "\nExpected environment variable does not match. Received:\n"
    puts $fileData
    exit 1
}

set fp [open $gitHubOutputFile r]
set fileData [read $fp]
close $fp

set expectedValue "key=Linux-php-8.1.1-composer-locked-long-files-hash\n"

if { $expectedValue != $fileData } {
    puts "\nExpected output variable does not match. Received:\n"
    puts $fileData
    exit 1
}

# Clean up
file delete $gitHubEnvFile
file delete $gitHubOutputFile
