#!/usr/bin/env -S expect -f

set gitHubEnvFile cache_key_04.txt
file delete $gitHubEnvFile
set ::env(GITHUB_ENV) $gitHubEnvFile

set timeout 3
spawn ../../bin/cache_key.sh "Linux" "8.1.1" "lowest" "--ignore-platform-reqs --optimize-autoloader" "long-files-hash"
match_max 100000

expect -exact "::debug::Cache primary key is 'Linux-php-8.1.1-composer---ignore-platform-reqs---optimize-autoloader-lowest-long-files-hash'"
expect -exact "::debug::Cache restore keys are 'Linux-php-8.1.1-composer---ignore-platform-reqs---optimize-autoloader-lowest-'"
expect -exact "::set-output name=key::Linux-php-8.1.1-composer---ignore-platform-reqs---optimize-autoloader-lowest-long-files-hash"
expect eof

set fp [open $gitHubEnvFile r]
set fileData [read $fp]
close $fp

set expectedValue "CACHE_RESTORE_KEY<<EOF
Linux-php-8.1.1-composer---ignore-platform-reqs---optimize-autoloader-lowest-
EOF
"

if { $expectedValue != $fileData } {
    puts "\nExpected environment variable does not match. Received:\n"
    puts $fileData
    exit 1
}
