#!/usr/bin/env -S expect -f

set gitHubEnvFile cache_key_01.txt
file delete $gitHubEnvFile
set ::env(GITHUB_ENV) $gitHubEnvFile

set timeout 3
spawn ../../bin/cache_key.sh
match_max 100000

expect -exact "::debug::Cache primary key is 'php-composer-locked'"
expect -exact "::debug::Cache restore keys are 'php-composer-locked-'"
expect -exact "::set-output name=key::php-composer-locked"
expect eof

set fp [open $gitHubEnvFile r]
set fileData [read $fp]
close $fp

set expectedValue "CACHE_RESTORE_KEY<<EOF
php-composer-locked-
EOF
"

if { $expectedValue != $fileData } {
    puts "\nExpected environment variable does not match. Received:\n"
    puts $fileData
    exit 1
}
