#!/usr/bin/env -S expect -f

set gitHubEnvFile cache_key_05.txt
file delete $gitHubEnvFile
set ::env(GITHUB_ENV) $gitHubEnvFile

set timeout 3
spawn ../../bin/cache_key.sh "Linux" "8.1.1" "locked" "" "long-files-hash" "my-custom-key"
match_max 100000

expect -exact "::debug::Cache primary key is 'my-custom-key'"
expect -exact "::debug::Cache restore keys are ''"
expect -exact "::set-output name=key::my-custom-key"
expect eof

set fp [open $gitHubEnvFile r]
set fileData [read $fp]
close $fp

set expectedValue "CACHE_RESTORE_KEY<<EOF

EOF
"

if { $expectedValue != $fileData } {
    puts "\nExpected environment variable does not match. Received:\n"
    puts $fileData
    exit 1
}
