#!/usr/bin/env -S expect -f

set gitHubOutputFile composer_paths_08.txt
set ::env(GITHUB_OUTPUT) $gitHubOutputFile

set timeout 3
spawn ../../bin/composer_paths.sh "" "../fixtures/out-of-sync-lock"
match_max 100000

expect "::debug::Composer path is '*'\r
::debug::Composer version *\r
::debug::Composer cache directory found at '*'\r
::debug::File composer.json found at '../fixtures/out-of-sync-lock/composer.json'\r
::debug::File composer.lock path computed as '../fixtures/out-of-sync-lock/composer.lock'\r
"
expect eof

set fp [open $gitHubOutputFile r]
set fileData [read $fp]
close $fp

set expectedValue "command=*\r
cache-dir=*\r
json=../fixtures/out-of-sync-lock/composer.json\r
lock=../fixtures/out-of-sync-lock/composer.lock\n
"

if { $expectedValue != $fileData } {
    puts "\nExpected output variable does not match. Received:\n"
    puts $fileData
    exit 1
}

# Clean up
file delete $gitHubOutputFile
