#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "lowest"
match_max 100000

expect -exact "::debug::Using the following Composer command: 'composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable '"
expect "Updating dependencies"
expect "Installing dependencies from lock file (including require-dev)"
expect "Generating autoload files"
expect eof
