#!/usr/bin/env -S expect -f

set gitHubOutputFile composer_paths_09.txt
set ::env(GITHUB_OUTPUT) $gitHubOutputFile

set timeout 3
spawn ../../bin/composer_paths.sh "../fixtures/composer.phar"
match_max 100000

expect "::debug::Composer path is '../fixtures/composer.phar'\r
::debug::Composer version 2.2.2 2021-12-29 14:15:27\r
::debug::Composer cache directory found at '*'\r
::debug::File composer.json found at './composer.json'\r
::debug::File composer.lock path computed as './composer.lock'\r
"
expect eof

set fp [open $gitHubOutputFile r]
set fileData [read $fp]
close $fp

set expectedValue "command=../fixtures/composer.phar\r
cache-dir=*\r
json=./composer.json\r
lock=./composer.lock\r
"

if { $expectedValue != $fileData } {
    puts "\nExpected output variable does not match. Received:\n"
    puts $fileData
    exit 1
}

# Clean up
file delete $gitHubOutputFile
