#!/usr/bin/env -S expect -f

# For testing outputs variables written to GITHUB_OUTPUT
set gitHubOutputFile composer_paths_05.txt
set ::env(GITHUB_OUTPUT) $gitHubOutputFile

set timeout 3
spawn ../../bin/composer_paths.sh "" "../fixtures/no-lock-file"
match_max 100000

expect "::debug::Unable to find composer.lock at '../fixtures/no-lock-file/composer.lock'\r
::debug::Composer path is '*'\r
::debug::Composer version *\r
::debug::Composer cache directory found at '*'\r
::debug::File composer.json found at '../fixtures/no-lock-file/composer.json'\r
::debug::File composer.lock path computed as ''\r
"
expect eof

# Confirm environment variables.
set fp [open $gitHubOutputFile r]
set fileData [read $fp]
close $fp

set expectedValue "composer_command=*\r
cache-dir=*\r
json=../fixtures/no-lock-file/composer.json\r
lock=\r
"

if { $expectedValue != $fileData } {
    puts "\nExpected output variable does not match. Received:\n"
    puts $fileData
    exit 1
}

# Clean up
file delete $gitHubOutputFile
