#!/usr/bin/env -S expect -f

# Clean up
file delete -force ../fixtures/with-lock-file/vendor

set timeout 3
spawn ../../bin/composer_install.sh "lowest" "--ignore-platform-reqs --optimize-autoloader" "../fixtures/with-lock-file"
match_max 100000

expect -exact "::debug::Using the following Composer command: 'composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable --ignore-platform-reqs --optimize-autoloader --working-dir ../fixtures/with-lock-file'"
expect "Updating dependencies"
expect "Generating optimized autoload files"
expect eof
