#!/usr/bin/env -S expect -f

# For testing outputs variables written to GITHUB_OUTPUT
set gitHubOutputFile composer_paths_08.txt
set ::env(GITHUB_OUTPUT) $gitHubOutputFile

set timeout 3
spawn ../../bin/composer_paths.sh "" "../fixtures/out-of-sync-lock"
match_max 100000

expect "::debug::Composer path is '*'\r
::debug::Composer version *\r
::debug::Composer cache directory found at '*'\r
::debug::File composer.json found at '../fixtures/out-of-sync-lock/composer.json'\r
::debug::File composer.lock path computed as '../fixtures/out-of-sync-lock/composer.lock'\r
"
expect eof

# Verify output variables have been set correctly.
set fp [open $gitHubOutputFile r]
set fileData [read $fp]
close $fp

if {[regexp {^composer_command=\S*\s*cache-dir=\S*\s*json=\.\./fixtures/out-of-sync-lock/composer\.json\s*lock=\.\./fixtures/out-of-sync-lock/composer\.lock\s*$} $fileData] == 0} {
    puts "\nExpected output variable does not match. Received:\n"
    puts $fileData
    exit 1
}

# Clean up
file delete $gitHubOutputFile
