#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_paths.sh "" "../fixtures/out-of-sync-lock"
match_max 100000

expect "::debug::Composer path is '*'\r
::debug::Composer version *\r
::debug::Composer cache directory found at '*'\r
::debug::File composer.json found at '../fixtures/out-of-sync-lock/composer.json'\r
::debug::File composer.lock path computed as '../fixtures/out-of-sync-lock/composer.lock'\r
::set-output name=command::*\r
::set-output name=cache-dir::*\r
::set-output name=json::../fixtures/out-of-sync-lock/composer.json\r
::set-output name=lock::../fixtures/out-of-sync-lock/composer.lock\r
"
expect eof
