#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "" "--ignore-platform-reqs --optimize-autoloader" "../fixtures/with-lock-file"
match_max 100000

expect -exact "::debug::Using the following Composer command: 'composer install --no-interaction --no-progress --ansi --ignore-platform-reqs --optimize-autoloader --working-dir ../fixtures/with-lock-file'"
expect "Installing dependencies from lock file (including require-dev)"
expect "Generating optimized autoload files"
expect eof
