#!/usr/bin/env -S expect -f

# Clean up
file delete -force ../fixtures/with-lock-file/vendor

set timeout 3
spawn ../../bin/composer_install.sh "highest" "" "../fixtures/with-lock-file"
match_max 100000

expect -exact "::debug::Using the following Composer command: 'composer update --no-interaction --no-progress --ansi --working-dir ../fixtures/with-lock-file'"
expect "Updating dependencies"
expect "Generating autoload files"
expect eof
