#!/usr/bin/env -S expect -f

# For testing outputs variables written to GITHUB_OUTPUT
set gitHubOutputFile composer_paths_09.txt
set ::env(GITHUB_OUTPUT) $gitHubOutputFile

set timeout 3
spawn ../../bin/composer_paths.sh "../fixtures/composer.phar"
match_max 100000

expect "::debug::Composer path is '../fixtures/composer.phar'\r
::debug::Composer version 2.2.18 2022-08-20 11:33:38\r
::debug::Composer cache directory found at '*'\r
::debug::File composer.json found at './composer.json'\r
::debug::File composer.lock path computed as './composer.lock'\r
"
expect eof

# Verify output variables have been set correctly.
set fp [open $gitHubOutputFile r]
set fileData [read $fp]
close $fp

if {[regexp {^composer_command=\.\./fixtures/composer\.phar\s*cache-dir=\S*\s*json=\./composer\.json\s*lock=\./composer\.lock\s*$} $fileData] == 0} {
    puts "\nExpected output variable does not match. Received:\n"
    puts $fileData
    exit 1
}

# Clean up
file delete $gitHubOutputFile
