#!/usr/bin/env -S expect -f

set timeout 3
# So we don't find a composer.lock in current dir
cd ..
spawn ../bin/composer_paths.sh "" "fixtures/with-lock-file"
match_max 100000

expect "::debug::Composer path is '*'\r
::debug::Composer version *\r
::debug::Composer cache directory found at '*composer*'\r
::debug::File composer.json found at 'fixtures/with-lock-file/composer.json'\r
::debug::File composer.lock path computed as 'fixtures/with-lock-file/composer.lock'\r
"
expect eof
