#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_paths.sh "" "../fixtures/no-lock-file"
match_max 100000

expect "::debug::Unable to find composer.lock at '../fixtures/no-lock-file/composer.lock'\r
::debug::Composer path is '*'\r
::debug::Composer cache directory found at '*'\r
::debug::File composer.json found at '../fixtures/no-lock-file/composer.json'\r
::debug::File composer.lock path computed as ''\r
::set-output name=command::*\r
::set-output name=cache-dir::*\r
::set-output name=json::../fixtures/no-lock-file/composer.json\r
::set-output name=lock::\r
"
expect eof
