#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "locked" "--ignore-platform-reqs --optimize-autoloader"
match_max 100000

expect -exact "::debug::Using the following Composer command: 'composer install --no-interaction --no-progress --ansi --ignore-platform-reqs --optimize-autoloader'"
expect "Installing dependencies from lock file (including require-dev)"
expect "Generating optimized autoload files"
expect eof
