#!/usr/bin/env -S expect -f

# For testing outputs variables written to GITHUB_OUTPUT
set gitHubOutputFile php_version_01.txt
set ::env(GITHUB_OUTPUT) $gitHubOutputFile

set timeout 3
spawn ../../bin/php_version.sh
match_max 100000

expect "::debug::PHP path is '*'\r
::debug::PHP version is '*.*.*'\r
"
expect eof

# Verify output variables have been set correctly.
set fp [open $gitHubOutputFile r]
set fileData [read $fp]
close $fp

if {[regexp {^path=\S*\s*version=\d*\.\d*\.\d*\s*$} $fileData] == 0} {
    puts "\nExpected output variable does not match. Received:\n"
    puts $fileData
    exit 1
}

# Clean up
file delete $gitHubOutputFile
